import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useSelector, useDispatch } from 'react-redux';
import { decrement, increment } from '../slices/counterSlice';
import { RootState } from '../store';

export default function Home() {
  const count = useSelector((state: RootState) => state.counter.value);
  const dispatch = useDispatch();

  //dùng axios để gọi api 'https://api.tala.xyz/v2/orders?page=2&limit=10'
  //https://api.tala.xyz/v2/orders?page=2&limit=10
  const request = async () => {
    const response = await fetch('/api/tala', {
      method: 'POST',
      mode: 'cors',
      cache: 'no-cache',
      credentials: 'same-origin',
      headers: {
        'Content-Type': 'application/json',
      },
      redirect: 'follow',
      referrerPolicy: 'no-referrer',
      body: JSON.stringify({ page: 2, limit: 10 }),
    });
    if (response.status === 200) {
      dispatch(increment());
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Value 0{count}</h1>
        <button onClick={() => dispatch(increment())}>Increament</button>
        <button onClick={() => dispatch(decrement())}>Decrement</button>
      </main>
    </div>
  );
}
