import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useSelector, useDispatch } from 'react-redux';
import { decrement, increment } from '../slices/counterSlice';
import { RootState } from '../store';
import axios from 'axios';

export default function Home() {
  const count = useSelector((state: RootState) => state.counter.value);
  const dispatch = useDispatch();

  //dùng axios để gọi api 'https://api.tala.xyz/v2/orders?page=2&limit=10'
  axios
    .get(curl 'https://api.tala.xyz/v2/orders?page=2&limit=10' \
    -H 'x-access-token: eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIxMDAwODQwMDciLCJpYXQiOjE2Njc5MDA0NDYsImV4cCI6MTY2ODA3MzI0NiwiaXNzIjoiaHR0cHM6Ly90aWtpLnZuIiwiY3VzdG9tZXJfaWQiOiIxMDAwODQwMDciLCJlbWFpbCI6ImFkbWluQHRpa2kudm4iLCJjbGllbnRfaWQiOiJ0aWtpLXNzbyIsIm5hbWUiOiIxMDAwODQwMDciLCJzY29wZSI6InNzbyJ9.UQDV8aSHenERoBAuRJP-iWLU8rFW_OL625q47Yn4FQ1ZvMdzZa8Fe6DHk2PNWL-HEChxK5GRh2C3zinE4VBgJUteJSAGRg7JqHue0vkAzX1B12wU3IhX5mAW_nG-_efY5fpJ1wW_FYzlZLgvPAQwzYaArnAsQw-qzZyuM0HPrBoSh3QYRFEpFIpsx1-ISRAbZTddDp6UTvkyDcsDTECPBxRMOZWFuVUnqKoqhwxAZKYR9fb_nDWx17IhXaP4KpUuPMCKMFqsTXyD1tfTGU0U9bN5pGoOOoUJ-nBZuESJeOWzTfxpmkdT6B05EgenkvVE5uA6jBh2kzeqnolSM7MSEJL649YQMlXFhlz7szzRoxYcrqbFGnCsOqyY9Wv1EsW60UFyyl-05PdwHulW63YhpBgJN96n1tNvZMxk2AsyxCpqtHmmqMtZXI-kwIgBFkJ96FrSz3VkziNftBLl3w2yUEB4GZ8tw0EZNZg13jjwm0OeICGSjq2c6ANBnuCp6EKMnmp52EKNkZSTiW7BT-nghwKh5oJynzKZPfV1XmulEe8bOb1X9doZiC0L3hCIs4-OTJYDhO0BcHvqAgqyvZrciY0JOlNs9GcvGkkDTRt0c3a3J2-ezUqnM_aLyCWoH2_Vs2OxZuMTUXsTdkb6_rwN_6udttAGn9gAvy9YdY_rxIo'
  )
    .then((response) => response.data)
    .catch((error) => console.log(error));

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Value 0{count}</h1>
        <button onClick={() => dispatch(increment())}>Increament</button>
        <button onClick={() => dispatch(decrement())}>Decrement</button>
      </main>
    </div>
  );
}
