import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useSelector, useDispatch } from 'react-redux';
import { decrement, increment } from '../slices/counterSlice';
import { RootState } from '../store';
import axios from 'axios';

export default function Home() {
  const count = useSelector((state: RootState) => state.counter.value);
  const dispatch = useDispatch();

  //dùng axios để gọi api 'https://api.tala.xyz/v2/orders?page=2&limit=10'
  axios
    .get('https://api.tala.xyz/v2/orders?page=2&limit=10')
    .then((response) => console.log(response.data))
    .catch((error) => console.log(error));

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Value 0{count}</h1>
        <button onClick={() => dispatch(increment())}>Increament</button>
        <button onClick={() => dispatch(decrement())}>Decrement</button>
      </main>
    </div>
  );
}
